apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims","persistentvolumes","events"]
    verbs: ["get","list","update","watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses","volumeattachments","volumeattachments/status","csinodes"]
    verbs: ["get","list","update","watch"]
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-default
subjects:
  - kind: ServiceAccount
    name: default 
    namespace: default
roleRef:
  kind: ClusterRole
  name: storage-admin
